import { createContext, useContext, useState, ReactNode } from "react";
import { 
  Alert, 
  Modal, 
  View, 
  Text, 
  TextInput, 
  TouchableOpacity, 
  StyleSheet, 
  ActivityIndicator, 
  Linking,
  KeyboardAvoidingView,
  Platform,
  TouchableWithoutFeedback,
  Keyboard
} from "react-native";
import { useAuth } from "./AuthContext";
import { grantMembership, isContentPurchased, checkMembershipStatus } from "../services/purchaseService";
import { MEMBERSHIP_PRICE, COLORS } from "../constants";

interface PaymentContextType {
  processPayment: (amount: number, description: string, contentId?: string, type?: "notes" | "pyq" | "membership") => Promise<boolean>;
  processMembership: () => Promise<boolean>;
  isProcessing: boolean;
}

const PaymentContext = createContext<PaymentContextType>({
  processPayment: async () => false,
  processMembership: async () => false,
  isProcessing: false,
});

const API_URL = process.env.EXPO_PUBLIC_API_URL || "http://localhost:3000";

export function PaymentProvider({ children }: { children: ReactNode }) {
  const [isProcessing, setIsProcessing] = useState(false);
  const { user, refreshUser } = useAuth();

  // UTR Modal states
  const [utrModalVisible, setUtrModalVisible] = useState(false);
  const [utrInput, setUtrInput] = useState("");
  const [isSubmittingUtr, setIsSubmittingUtr] = useState(false);
  const [paymentAmount, setPaymentAmount] = useState(0);
  
  const [currentTransactionId, setCurrentTransactionId] = useState("");
  const [currentContentId, setCurrentContentId] = useState<string | undefined>(undefined);
  const [currentType, setCurrentType] = useState<"notes" | "pyq" | "membership" | undefined>(undefined);
  const [pendingResolve, setPendingResolve] = useState<((val: boolean) => void) | null>(null);

  const fetchWithTimeout = async (url: string, options: RequestInit, timeout = 15000) => {
    const controller = new AbortController();
    const id = setTimeout(() => controller.abort(), timeout);
    try {
      const res = await fetch(url, { ...options, signal: controller.signal });
      clearTimeout(id);
      return res;
    } catch {
      clearTimeout(id);
      throw new Error("Network request failed");
    }
  };

  const getAuthToken = async (): Promise<string | null> => {
    try {
      const { auth } = await import("../constants/firebase");
      const token = await auth.currentUser?.getIdToken();
      return token || null;
    } catch {
      return null;
    }
  };

  const pollPurchaseStatus = async (
    contentId?: string,
    type?: "notes" | "pyq" | "membership"
  ): Promise<boolean> => {
    if (!user) return false;
    let attempts = 0;
    const maxAttempts = 15; // 30 seconds total

    while (attempts < maxAttempts) {
      if (type === "membership") {
        const hasMembership = await checkMembershipStatus(user.id);
        if (hasMembership) return true;
      } else if (contentId) {
        const isPurchased = await isContentPurchased(user.id, contentId);
        if (isPurchased) return true;
      }

      await new Promise((resolve) => setTimeout(resolve, 2000));
      attempts++;
    }
    return false;
  };

  const processPayment = async (
    amount: number,
    description: string,
    contentId?: string,
    type?: "notes" | "pyq" | "membership"
  ): Promise<boolean> => {
    if (!user) {
      Alert.alert("Login Required", "Please login to make a purchase");
      return false;
    }

    setIsProcessing(true);
    try {
      const token = await getAuthToken();
      if (!token) {
        Alert.alert("Error", "Could not authenticate. Please login again.");
        return false;
      }

      // 1. Call backend to create the direct UPI order record
      const orderRes = await fetchWithTimeout(`${API_URL}/api/payments/create-upi-order`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
          "ngrok-skip-browser-warning": "true",
        },
        body: JSON.stringify({
          contentId,
          amount,
          type: type || (contentId ? "notes" : "membership"),
        }),
      });

      if (!orderRes.ok) {
        const errorBody = await orderRes.text();
        console.error("Create UPI order failed:", orderRes.status, errorBody);
        Alert.alert("Error", `Failed to initiate payment (${orderRes.status})`);
        return false;
      }

      const { upiUrl, transactionId } = await orderRes.json();
      if (!upiUrl) {
        Alert.alert("Error", "UPI link not generated by the server.");
        return false;
      }

      // 2. Open UPI deep link
      try {
        await Linking.openURL(upiUrl);
      } catch (err) {
        console.warn("Failed to open UPI link directly", err);
        Alert.alert(
          "UPI App Redirect",
          `We couldn't launch your UPI app automatically. Please open GPay, PhonePe, FamPay, or Paytm, and pay manually to:\n\nUPI ID: ${process.env.EXPO_PUBLIC_UPI_ID || "royalfantasyyt@okicici"}\nAmount: ₹${amount}\n\nMake sure to copy the 12-digit UTR transaction code after paying.`
        );
      }

      // 3. Show the UTR Modal and await resolution
      setPaymentAmount(amount);
      setCurrentTransactionId(transactionId);
      setCurrentContentId(contentId);
      setCurrentType(type || (contentId ? "notes" : "membership"));
      setUtrInput("");
      setUtrModalVisible(true);

      return new Promise<boolean>((resolve) => {
        setPendingResolve(() => resolve);
      });

    } catch (error: any) {
      Alert.alert("Payment Failed", error?.message || "Something went wrong");
      setIsProcessing(false);
      return false;
    }
  };

  const processMembership = async (): Promise<boolean> => {
    return processPayment(MEMBERSHIP_PRICE, "Brain Bank Lifetime Membership", undefined, "membership");
  };

  const handleUtrSubmit = async () => {
    if (!/^\d{12}$/.test(utrInput)) {
      Alert.alert("Invalid UTR", "UPI Reference Number (UTR) must be exactly 12 numeric digits.");
      return;
    }

    setIsSubmittingUtr(true);
    try {
      const token = await getAuthToken();
      if (!token) {
        Alert.alert("Error", "Failed to retrieve auth token.");
        setIsSubmittingUtr(false);
        return;
      }

      const verifyRes = await fetchWithTimeout(`${API_URL}/api/payments/verify-upi`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
          "ngrok-skip-browser-warning": "true",
        },
        body: JSON.stringify({
          transactionId: currentTransactionId,
          utr: utrInput,
        }),
      });

      if (!verifyRes.ok) {
        const errorText = await verifyRes.text();
        Alert.alert("Verification Failed", errorText || "Failed to submit payment details.");
        setIsSubmittingUtr(false);
        return;
      }

      const verifyData = await verifyRes.json();
      setUtrModalVisible(false);

      Alert.alert(
        verifyData.status === "completed" ? "Payment Successful! 🎉" : "Details Submitted",
        verifyData.message
      );

      const success = await pollPurchaseStatus(currentContentId, currentType);
      if (success) {
        await refreshUser();
        if (pendingResolve) pendingResolve(true);
      } else {
        if (pendingResolve) pendingResolve(false);
      }
    } catch (err: any) {
      Alert.alert("Verification Error", err.message || "An error occurred during verification.");
      if (pendingResolve) pendingResolve(false);
    } finally {
      setIsSubmittingUtr(false);
      setIsProcessing(false);
      setPendingResolve(null);
    }
  };

  const handleCancel = () => {
    setUtrModalVisible(false);
    setIsProcessing(false);
    if (pendingResolve) {
      pendingResolve(false);
      setPendingResolve(null);
    }
  };

  return (
    <PaymentContext.Provider value={{ processPayment, processMembership, isProcessing }}>
      {children}
      <Modal
        visible={utrModalVisible}
        transparent={true}
        animationType="slide"
        onRequestClose={handleCancel}
      >
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
          <KeyboardAvoidingView
            behavior={Platform.OS === "ios" ? "padding" : "height"}
            style={styles.modalOverlay}
          >
            <View style={styles.modalContent}>
              <Text style={styles.modalTitle}>⚠️ Enter UTR to Verify</Text>
              
              <Text style={styles.instructionsText}>
                We opened your UPI app to pay <Text style={styles.amountText}>₹{paymentAmount}</Text>.
              </Text>

              <Text style={styles.subInstructionsText}>
                Copy the <Text style={{fontWeight: "bold"}}>12-digit UPI Reference / UTR Number</Text> from Google Pay, PhonePe, FamPay, or Paytm transaction history and paste it below to verify your payment:
              </Text>

              <TextInput
                style={styles.input}
                value={utrInput}
                onChangeText={setUtrInput}
                placeholder="Enter 12-digit UTR Number"
                placeholderTextColor="#999999"
                keyboardType="numeric"
                maxLength={12}
              />

              {isSubmittingUtr ? (
                <ActivityIndicator size="large" color={COLORS.primary} style={styles.loader} />
              ) : (
                <View style={styles.buttonContainer}>
                  <TouchableOpacity style={styles.cancelButton} onPress={handleCancel}>
                    <Text style={styles.cancelButtonText}>Cancel</Text>
                  </TouchableOpacity>
                  <TouchableOpacity style={styles.submitButton} onPress={handleUtrSubmit}>
                    <Text style={styles.submitButtonText}>Submit & Unlock</Text>
                  </TouchableOpacity>
                </View>
              )}
            </View>
          </KeyboardAvoidingView>
        </TouchableWithoutFeedback>
      </Modal>
    </PaymentContext.Provider>
  );
}

export const usePayment = () => useContext(PaymentContext);

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    maxWidth: 350,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.primary || "#674bb5",
    marginBottom: 16,
    textAlign: "center",
  },
  instructionsText: {
    fontSize: 16,
    color: "#333333",
    textAlign: "center",
    marginBottom: 8,
  },
  amountText: {
    fontWeight: "bold",
    color: COLORS.primary || "#674bb5",
  },
  subInstructionsText: {
    fontSize: 14,
    color: "#666666",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 20,
  },
  input: {
    width: "100%",
    height: 48,
    borderWidth: 1,
    borderColor: "#cccccc",
    borderRadius: 8,
    paddingHorizontal: 16,
    fontSize: 16,
    color: "#333333",
    backgroundColor: "#fafafa",
    textAlign: "center",
    marginBottom: 20,
  },
  loader: {
    marginVertical: 12,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cccccc",
    backgroundColor: "#ffffff",
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666666",
  },
  submitButton: {
    flex: 1.5,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: COLORS.primary || "#674bb5",
  },
  submitButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#ffffff",
  },
});
